### ISSUE TITLE
How to solve this error?

### ISSUE THREAD

**Issue by Zemin-Arzch** [Simeonedef/Time-Series_Imaging_Forecasting#2]
X_train,y_train=model.sequence_splitter(serie_train)
**AttributeError: 'noHW_LSTM' object has no attribute 'sequence_splitter'**

serie_train and serie_test in wrong order in
`77 X_train,y_train=model.sequence_splitter(serie_train)
78  X_test,y_test = model.sequence_splitter(serie_test)` in noHW_LSTM_example.py

**Comment by Zemin-Arzch** [comment]
Maybe there is no attribute named sequence_splitter in class'noHW_LSTM' but in 'utils'. I have few experience with using pyCharm.

**Comment by Simeonedef** [comment]
Hey ! 

Thanks for checking out the repo :)

The noHW_LSTM_example.py file is actually deprecated, my bad, I completely forgot to update all those <model>_example files as they were no longer used past the initial implementations. The way it's meant to be used, is to call it through example_time_series.py like so:

```
python script\example_time_series.py --model="LSTM"
```


If you want to make the noHW_LSTM_example.py work, then simply copy paste the relevant bit of the code from example_time_series.py into it. i.e:

Replace lines 65 to 84 in example_time_series.py:
```
#Scale Series
MMscaler = MinMaxScaler(feature_range=(-1, 1))
serie_train = MMscaler.fit_transform(serie_train.reshape(-1,1)).flatten()
serie_test = MMscaler.fit_transform(serie_test.reshape(-1,1)).flatten()

#%% Forecasting
from noHW_LSTM import *

print("Initializing noHW_LSTM object")
model = noHW_LSTM(inpt_window,outp_window)

#Create test/train sets
X_test,y_test=model.sequence_splitter(serie_train)
X_train,y_train = model.sequence_splitter(serie_test)

#Build model
NN_model = model.build_NN()

#Fit model
history,y_pred,y_true,MSE=model.fit_NN(X_train,y_train,X_test,y_test,epochs=5,bsize=64)
```

With those lines from example_time_series.py:
```
from noHW_LSTM import *
#You can replace this below with wherever you want the predictions csv file to be (but make sure the directory exists otherwise it will throw an error)
preds_filepath = "predictions_dir"

print("Initializing LSTM object")
model = noHW_LSTM(inp_window=inpt_window,out_window=outp_window)
print("Starting LSTM training")
history,y_pred,y_true,MSE = model.fit_NN(serie_train[0:n],serie_test[0:n], epochs=5, bsize=64, p_filepath=preds_filepath, callbacks=False)

show_result(y_true, y_pred, full=False)
```

I'll update or remove those files later today, thanks for pointing it out !

**Comment by Simeonedef** [comment]
Fix has been pushed.

All <model>_example.py files have been fixed.

They need to be run from the repo's root directory :)
